language: python
python:
  - "2.7"
cache: pip
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - pip install --upgrade setuptools
  - pip install --upgrade codecov pytest pytest-cov
  - pip install --upgrade pytest-cov
  - pip install oauth2client
  - pip install .
script:
  - e "$EE_PRIVATE_KEY" | base64 -d > privatekey.pem
  - pwd
  - ls
  - py.test --cov sql2gee --cov-report xml --cov-report term
after_success:
  - codecov
