language: python
python:
  - "2.7"
cache: pip
install:
  - sudo apt-get install ntp
  - sudo apt-get install openssl
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - pip install --upgrade setuptools
  - pip install --upgrade codecov pytest pytest-cov
  - pip install --upgrade pytest-cov
  - pip install oauth2client
  - pip install oauth2
  - pip instsll pil
  - pip install 'pyOpenSSL>=0.11'
  - pip install pyCrypto
  - pip install google-api-python-client
  - pip install .
script:
  - ntpdate -s ntp.ubuntu.com
  - echo -e "$EE_PRIVATE_KEY" | base64 -d > privatekey.pem
#  - openssl pkcs12 -in $EE_PRIVATE_KEY -nodes -nocerts > privatekey.pem
  - pwd
  - ls
  - py.test --cov sql2gee --cov-report xml --cov-report term
after_success:
  - codecov
